# Site settings
title: Anson Chong | About
description: A personal portfolio of a talented software engineer
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "/chong-anson.github.io/portfolio" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anson Chong
# user_description: 
user_title: I am a software engineer who was born and raised in Hong Kong.
email: ansonchongch@gmail.com
github_username:  Chong-anson

exclude: ['package.json', 'src' , 'node_modules']
