# Site settings
title: Anson Chong | About
description: A personal portfolio of a talented software engineer
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anson Chong
# user_description: 
user_title: A software engineer based in Seattle. Also a mechanical engineer and volleyball player.
email: ansonchongch@gmail.com
github_username:  Chong-anson

exclude: ['package.json', 'src' , 'node_modules']
